# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "quantal64"

  # Name for the VM
  config.vm.host_name = "midgardproject"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "https://github.com/downloads/roderik/VagrantQuantal64Box/quantal64.box"

  # Assign this VM to a host-only network IP, allowing you to access it
  # via the IP. Host-only networks can talk to the host machine as well as
  # any other machines on the same network, but cannot be accessed (through this
  # network interface) by any external networks.
  config.vm.network :hostonly, "192.168.33.10"

  Vagrant::Config.run do |config|
    config.vm.forward_port 8001, 8181
    config.vm.share_folder("midgardmvc", "/opt/midgardmvc", "../..", :nfs => true)
  end

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.module_path = "../puppet/modules"
    puppet.manifest_file  = "midgardmvc.pp"
  end
end
